* [2020-3-7 Sat] - abstract draft
**
Pyramidal neurons in neocortex have complex input-output relationships that depend on their morhpologies, active and
passive channel distributions, and the nature of their inputs, and which cannot be replicated by their simple 
integrate-and-fire analogs. Measures of the complex impedance response across neurons' dendritic arbors, such as 
resonance and the phase response, can provide intraneuronal functional maps reflecting their intrinsic dynamics and excitability. 
Experimental studies of dendritic impedance show that pyramidal neurons in hippocampal CA1 and neocrotex exhibit distance-dependent
relationships for the resonance and the phase responses with respect to the soma. We present a detailed study of
the complex impedance profiles of biophysically detailed models of neocortical layer 5 pyramidal neurons from 
across neocortex.  While none of these models were designed to fit the impedance response directly, two closely 
recapitulate the distance-dependent relationships of the complex impedance response. The  impedance response is also
dynamically tunable via the activity-dependent expression of voltage-gated ion channels in the dendrites, like HCN channels
and M- and A-type K+ channels. We investigated the roles of different voltage-gated ion channels in tuning the impedance response,
showing that changes in HCN and M-type K+ channel conductances, both locally and across the dendritic arbor, can modulate the
impedance response, producing a wide range of profiles.  We also clearly demonstrate the impedance profile's dependence on cell
morphology.  Although a number of cell models exhibit impedance profiles that diverge from the experimental data, some have 
biologically plausible impedance profiles which may reflect regional variation or cells with different histories and therefore
differently tuned impedance responses. Given the dearth of experimental data on resonance in neocortical pyrmaidal neurons 
from different cortical regions, we hypothesize that neocortical pyramidal neurons have more diverse impedance profiles 
than previously assumed.

* [2020-3-10 Tue] - Introduction outline (cont to [2020-3-13 Fri])
** Neocortical pyramidal neurons
*** Main oupuuts of neocortex 
**** something about I/O relationship
*** Diversity:  
**** Naka2016-rn
"Before surveying the existent literature on layer 5 (L5) inhibitory neurons, we briefly review current
knowledge on the connectivity and physiological properties of L5 pyramidal cells (PCs), as it
provides important context for understanding L5 inhibitory circuits. One feature that distinguishes
L5 from other cortical layers is the diversity of its PCs, which send a myriad of long-range
projections to other cortical and sub-cortical structures (Levesque1996-hf, Veinante2000-gg,
Hattox2007-km, Aronoff2010-do, Harris2015-te). This simple anatomical fact establishes L5 as a primary 
cortical layer involved in the top-down control of other brain areas. Exactly how L5 circuits parse information to 
influence downstream circuits and control behavior is one of the central questions in neuroscience. Even though L5 is
conventionally thought of as primarily an output layer, L5 PCs also receive direct thalamocortical input (Agmon1992-mi,
Meyer2010-pe, Wimmer2010-lq, Oberlaender2012-fh, Rah2013-kr) and can be driven by thalamic activity alone (Constantinople2013-bq), 
suggesting that L5 is an important input layer as well. L5 PCs also receive input from all cortical layers and
are thus uniquely positioned to integrate nearly every local and afferent pathway in the cortex
(Markram2015-zg). Without exception, signals transmitted via these pathways invoke a mixture
of synaptic excitation and inhibition (reviewed in Isaacson2011-qs). Thus inhibition
onto L5 PCs, the focus of this review, is crucial for nearly every aspect of L5 function."
*** Active conductances
**** One of the main distinguishing factors between PT and IT neurons is the greater expression of 
voltage-gated ion channels, like HCN. Oswald2013-lh
**** "In responseto dynamic stimuli,  COM neurons act as low-pass filters, whereas CPn neurons act 
as bandpass filters, resonating in the theta frequency range (3– 6Hz)." Dembrow2010-lb
**** mediate coincidence detection Das2015-mh, Dewell2019-ra
**** Ih has also been shown to "interact with somato-dendritic structure to determine frequency response to
weak alternating electric field stimulation" Toloza2018-vh
****  "the inhibitory action of Ih was caused by its interaction with the delayed-rectifier M-type K1 current. In this manner, Ih can
enhance spike firing in response to an EPSP when spike threshold is low and can inhibit firing when spike threshold is high." George2009-ad
***** check w/ salva/joao - pretty sure this is the paper proposing that Ih modulation determines planning versus action 

** Impedance as comprehensive tool for studying subthreshold dynamics
*** As mentioned above, PT cells act as bandpass filters as characterized by their impedance profiles.
*** some  background on impedance Puil1986-uv, Jaffe1999-pb: 
**** complex function (resistance and reactance) from which can calculate the amplitude and phase 
**** input vs transfer
**** resonance - peak |Z| at some frequency - driven by inductive reactance imparted by voltage-gated ion channels like HCN, M-type K+, and K-type K+ channels
**** resonance strength (Q-factor as in Dewell2019-ra)
**** transfer frequency - resonance frequency of the transfer impedance amplitude 
**** leading phase response - changes in V preceed changes in I, driven by the balance of capacitive and inductive reactances
**** synchronous frequency - frequency at which V and I are synchronous

*** importance of impedance
**** resonance:  "Apart from invertebrate giant axons from where initial evidence came, direct evidence for the presence of electrical resonance
also came from experiments on numerous neuronal subtypes of the central and peripheral nervous system (Crawford1981-av, Puil1988-ca,
Hutcheon2000-gs, Pike et al., 2000). Subthreshold resonance in local responses and in dendrite-to-soma transfer endows neurons with the ability to
discriminate inputs based upon their frequency content."
**** phase response: "the impedance phase profile quantifies the temporal dynamics between voltage and current. It has been shown that presence
of inductive reactance in neuronal membrane causes the voltage response to lead the injected oscillatory current. The balance between capacitive and
inductive reactances determines both the optimal lead frequency and the frequency bandwidth over which the voltage leads the current, providing a
potential mechanism by which the subthreshold membrane dynamics of the neuron may maintain a phase relationship with an ongoing oscillation
(Mauro1961-ys, Cole, 1968, Sabah1969-at, Mauro1970-km, Hu2002-ga, Hu2009-qb, Ulrich2002-dd, Cook2007-cz, Narayanan2008-zw,
Vaidya2013-sx)." Das2017-nz
**** relation between subthreshold resonance and suprathreshold resonance via STA Das2015-mh
*** By determining these factors across the dendritic arbor, we can produce intraneuronal functional maps characterizing
the neuron's intrinsic dynamics and excitability Narayanan2012-hn 

** Experimental evidence of location dependence 
*** relationships between aspects of the complex impedance and distance from the soma have been described in pyramidal neurons from CA1 and neocortex
Das2017-nz, Narayanan2007-gw, Ulrich2002-dd, Dembrow2015-zb
**** first observed in PT neurons from somatosensory cortex.  Saw roughly linear relationships between distance and transfer impedance amplitude with
strength increasing with distance from the soma. Ulrich2002-dd
**** Dembrow et al additionally saw distance-dependence in the resoance frequency and phase response Dembrow2015-zb
**** in both above studies resonance and synchronous frequencies were found in the theta range (3-10 Hz), but also sampled a fairly small fraction of the 
dendritic arbor (120-280 um and 200-600 um respectively)

** dynamic tunability and degeneracy impedance profile
*** Tunability
**** dynamically tunable subthreshold resonance along the neuronal topograph (Magee2005-oq, Narayanan2007-gw, Narayanan2008-zw, Sjostrom2008-sz, 
Hu2009-qb, Rathour2012-am, Rathour2012-bu) Das2017-nz
**** LTP induces changes in impedance profile Narayanan2007-gw
*** Degeneracy:
**** "With reference to sub- and supra-threshold frequency selectivity in neurons, several studies have demonstrated multi-channel regulation
of somatodendritic spectral selectivity. Specifically, studies pertaining to sub-threshold resonance and phase dynamics have shown that impedance properties 
mediated by HCN channel could be significantly modulated by the presenc eof other sub-threshold conductances and by morphological characteristics 
(Hutcheon2000-gs, Hu2002-ga, 2009, Narayanan2008-zw, Zemankovics2010-zt, Rathour2012-bu, Dhupia2014-ad, Rathour2016-vv). While these studies
elucidated the role of individual conductances in modulating sub-threshold impedance properties, computational
frameworks have provided direct lines of evidence for degeneracy (Figures 2B,C) in active dendritic spectral tuning (Rathour2012-bu, Rathour2014-pl)." Das2017-nz
***** mainly studied in hippocampal neurons
*** role in disease: Ih altered in temporal lobe epilepsy Shin2008-za, Marcelin2009-vy

* [2020-3-12 Thu] 
** fairly satisfied w/ intro outline
** going with frontiers in neuroscience as target journal (in part becasue formatting is easy)

* [2020-3-13 Fri] - further along with intro
** may want to consolidate explanation and importance of impedance while separating amplitude/resonance and phase

* [2020-3-14 Sat] - finished with draft of intro, methods outline  (con't to [2020-3-16 Mon])
** General stuff:
*** All models have perviously been published and are freely available on modelDB
*** Simulations were performed using NEURON in Python Hines2009-qx
*** Code for simulation, analysis, and visualization was written in Python and MATLAB (Natick, Ma) and is available on GitHub (https://github.com/suny-downstate-medical-center/L5PYR_Resonance)

** Focus on 5  models
*** Kole2008-aj
**** Wistar rats, 2-4 weeks old, somatosensory cortex
**** channels densities were adjusted primarily to account for perisomatic spiking actiivity:
"The model included a high-voltage-activated K+ channel (Kv)16, a faster
low-voltage activated Kv1-like K+ channel (‘Kv1’), as described49, and a slowly-activating and non-inactivating M-type K+ channel (‘Km’)16. Potassium
channel densities were adjusted to obtain fast action potential repolarization
and large amplitude afterhyperpolarizations in the distal AIS13. The density of
Kv, Kv1 and Km were set to 20, 100 and 5 pS mm–2, respectively, in the soma,
dendrites and inter-nodal sections, and increased linearly with distance from
the axon hillock in the AIS to 2,000 pS mm–2 in the distal AIS and nodes for
Kv and Kv1, and to 50 pS mm–2 for Km. The K+ reversal potential was set
to –85 mV. Ih channels were included in the soma and dendrites with an
exponential increase in density with distance from the soma, and kinetics and
voltage dependence as described previously50." 50: Kole2006-bm
*** Acker2009-yj
**** Sprague–Dawley rats (postnatal day 21 [P21] to P33), frontal cortex
**** fit using voltage-sensitive dye imaging focusing on back-propagating APs in basal dendrites 
"The model was fit to experimental data using the
following approach: AP waveforms from simulations were analyzed
and amplitude data were averaged over the basal dendrites (Fig. 6B).
Half-widths and latencies were calculated in exactly the same way as
with the optical AP waveforms (Supplemental Fig. S5) and were
averaged over the model basal dendrites. The model data averaged
over the basal dendrites were taken as the fit data. AP amplitude ratios
TTX/Control and AP amplitude ratios 4-AP/Control were used to fit
the model.
**** channel distributions
. . . Basal dendritic sodium and A-type potassium conductance
distributions were assumed linear and were systematically varied over
a wide range over a four-dimensional parameter space to determine
the best-fit values of these model parameters (Supplemental Fig. S7).
Other parameters, such as delayed rectifier potassium conductance,
leak conductance, and somatic conductances, were manually varied to
find the lowest possible overall model fit. This was done by first
determining the sensitivities of AP amplitudes, half-widths, and latencies
 to each model parameter and using this information to modify
parameters and improve fits before finally fitting the basal sodium and
A-type potassium distributions. An automated optimization approach
based on a genetic algorithm (Keren et al. 2005), if feasible, would
allow a larger parameter space to be searched exhaustively and could
potentially lead to improved overall fits, something that could be
pursued in future studies."
*** Hay2011-if
**** P36 Wistar rat 
**** model fit to perisomatic and backpropagating spiking
**** channel distributions:
"Dendritic channel distribution. All dendritic channels
except for Ih, CaLVA and CaHVA were uniformly distributed. Ihchannels were distributed on the apical dendrites using an
exponential density function suggested in [13]: gsoma: ð{0:8696z 2:087: e x
323Þ, where x is the distance from the soma in mm, with gsoma = 1 pS/mm2 .
The density of Ih on the basal dendrites was set to be uniform as suggested in [10]."
10: Nevian2007-gw  13: Kole2006-bm
*** Neymotin2017-dr
**** might leave out or stick in supplements, both because mice and wonky
**** Mice (strain: C57Bl/6J; Jackson Laboratories) postnatal day (P) 21,
**** channel distributions:
Somatic and dendritic compartments
additionally contained CaL, CaN, BK, and HCN channels. KD was
present in the soma and at 20 times somatic density in the axon. The
axon contained only leak, Na, KA, Kdr, and KD ion channels. Basal
dendrites contained uniform density of all their channels. Apical
dendrite HCN channel density increased exponentially with distance
from soma until reaching the nexus with apical dendrite tufts, where
the HCN channel density plateaus at 0.00565 S/cm2 (Harnett et al.
2015). This exponential increase of HCN channel density within the
main apical trunk was set to gh·exp(d/h), where d is distance of the
apical dendrite compartment from soma and h is the length constant,
defined as dnexus/log(0.00565/gh), dnexus is distance from soma to
nexus (300 m), and gh is somatic HCN channel density. Harnett2015-sj
**** fitting was mostly focused on preisomatic spiking activity:
. Focusing on spike times, we also
provided some fitness function redundancy by using both
overall spiking rate (F–I), along with spike timing [instantaneous firing rate (IFR)]. The degree of redundancy of these two
measures was demonstrated in the final archive (Fig. 2, A and
C). We included subthreshold fit, determined initially by
PRAXIS, as an EMO fitness function as well so as not to lose
fitness for this criterion while optimizing for the others.
*** allen institute cell(s) Reimann2013-mg, Shai2015-ff, Markram2015-zg
**** based on data from primary visual cortex (V1) of C57BL/6 mice, P35-62
**** Modified version of an earlier model \citep{Hay2011-if}
**** major change to the original:"We change the Ih conductance to be constant in the dendritic tree, instead of exponentially increasing as a function of distance from
the soma, to fit the subthreshold data. The change to Ih conductance accounted for the differences between dendritic sag, dendritic resting membrane potential relative 
to the soma, and dendritic input resistance in our experiments compared to those in rat L5 somatosensory cortex."


** simulations 
*** Impedance Profiles:
****Each dendritic segment was stimulated with a subthreshold chirp-waveform current injection, and membrane potential was recorded
from the site of stimulation and at the soma.
***** For generating impednace profiles, the chirp-waveform instantaneous frequency changed linearly spanned 0.5-50 Hz over 50s.
***** For investigating bimodal phase response, the chirp-waveform spanned 0.5-100 Hz over 100s.
***** in experiments, typically 0.5-20 Hz (citations)
**** We computed Z$_{in}$ and Z$_c$ and associated measures from each of the recorded waveforms via \emph{Eq. 1-3}.
***** focused on six measures of the impedance response: 1) $|$Z$_{in}|$ resonance amplitude, 2) $|$Z$_{in}|$ resonance frequency,
3) $|$Z$_{in}|$ Q-factor, 4) $|$Z$_{c}|$ transfer frequency, 5) $\Phi_{in}$ leading phase bandwidth, and 6) $\Phi_{in}$ synchronous frequency. 
*** Influence of morphology
**** same parameters as above, used biophysics template and three morphologies from Hay2011-if
*** Ih and Im 
**** used cell model from Kole2008-aj, only one that had Ih and Im distributed throughout the dendritic arbor.
**** varied Ih and Im conductance in 5* increments up to +/- 20* either at the branch level or across the whole dendritic arbor 


* [2020-3-15 Sun] - bimodal phase response
** L5PCtemplate[0].apic[91].mat 
* [2020-3-16 Mon] - methods con't, added in sam's cell, going to add in allen institute
* [2020-3-17 Tue]
** bimodal phase response, a couple OK examples, not sure if it warrants figure / mentioning
* [2020-3-19 Thu] - working on putting figures together properly
* [2020-3-20 Fri] - finished up figures
** allen exmaple 1: 497233139, 2: 497232419
* [2020-3-21 Sat] 
** table of basic model info
* [2020-3-23 Mon] - methods done, on with results
** done with results text, still need to do figure captions
* [2020-4-6 Mon] - moved and cleaned up paper
** moved paper to overleaf, removed paper code from this repo - now just code and these notes.
*** 'moved paper to overleaf, removed paper code from this repo - now just code and notes'

* [2020-4-10 Fri] - discussion notes
** add to intro: Additionally, HCN plays an important role in
regulating neuronal excitability by setting resting membrane
potential (RMP) [5,6]

** biological plausibility
*** rat models all seem biologically plausible
**** resonance frequency, transfer frequency, synchronous frequency, and leading phase bandwidth all increase
 with distance from the soma along the dendritic arbor.
**** Two models, Acker & Antic and Hay et al., 2011, conform well to experimental data in L5 PT and resemble hipp PT
***** resonance and transfer frequencies in the theta range
***** synchronous frequencies in delta/theta range
***** roughly linear relationships with distance
**** third model (Kole et al) is very different, but not necessarily implausible
***** resonance frequencies from 10-50 Hz
***** transfer frequencies from 10-25 Hz
***** synchronous frequencies from 2-35 Hz
***** farthest dendritic compartment of this neuron is 1500 microns from the soma, in experimental studies of L5 PT cells,
farthest out is 700 microns (Dembrow2015-zb, Ulrich2002-dd)
***** at these distances in this cell, resonance frequencies are from 10-18 Hz, transfer frequencies from 11-15 Hz, synch freq 4-12 Hz, 
not too far off from experimental values!! (Dembrow2015-zb).

*** Neymotin et al - may be biologically possible
**** only model in which HCN channel density plateaus in the apical tufts
**** resonance transfer and synchronous frequencies below the nexus of the apical tufts are similar to experimental values and model
 was validated looking at somatic input resonance

*** dendritic impedance profiles for the ABA cells more of a mixed bag
**** 4927233139
**** resonance frequencies between 2-15 Hz, but resonance strength is so low that it would be indistinguishable from noise in experimental preparations
**** seemingly no relationship between input resonance frequency and transfer frequency to the soma
**** synchronous frequencies are all >35 Hz, which is not seen experimentally
**** 497232419
**** like Neymotin cell, input resonance frequency also plateau, but resonance strength is comparable to other cells studied here
and transfer frequency is not far offf from experimental observations
**** phase response is, as in the other ABA model, is fairly unusual

*** should be noted that these models were intended for use in large network simulations
**** constraining these models focused mainly on measures of perisomatic firing characteristics
**** ABA models deliberately simplified the channel distributions in the dendrites

** morphology, channel distribution, and dendritic impedance 
*** Although one of the ABA cells did not exhibit strong resonance, and neither may have biologically plausible impedance profiles 
by its constant channel densities in the dendrites they demonstrate that gradients in voltage-gated ion channel density are not 
necessary for gradients in the dendritic impedance profile.
**** The channel distributions in these models do suggest that realistic phase responses may require realistic channel distributions
*** The impedance profiles of the three cells with the same channel distributions (\emph{Fig. 7}) demonstrates that morphology has a
direct impact on all location-dependent relationships in the denritic impedance profile.
**** suggests that dendritic pruning seen during development \cite{Riccomagno2015-pq} and dendritic damage seen during traumatic 
brain injury \cite{Gao2011-xo} have impacts on the impedance profile of the entire neuron.
***** dendritic pruning during development may be one mechanism for tuning the impedance profile.

** Tunability and degeneracy of the impedance profile 
*** (from intro) Tunability
**** dynamically tunable subthreshold resonance along the neuronal topograph (Magee2005-oq, Narayanan2007-gw, Narayanan2008-zw, Sjostrom2008-sz, 
Hu2009-qb, Rathour2012-am, Rathour2012-bu) Das2017-nz
**** LTP induces changes in impedance profile Narayanan2007-gw
*** (from intro) Degeneracy:
**** "With reference to sub- and supra-threshold frequency selectivity in neurons, several studies have demonstrated multi-channel regulation
of somatodendritic spectral selectivity. Specifically, studies pertaining to sub-threshold resonance and phase dynamics have shown that impedance properties 
mediated by HCN channel could be significantly modulated by the presenc eof other sub-threshold conductances and by morphological characteristics 
(Hutcheon2000-gs, Hu2002-ga, 2009, Narayanan2008-zw, Zemankovics2010-zt, Rathour2012-bu, Dhupia2014-ad, Rathour2016-vv). While these studies
elucidated the role of individual conductances in modulating sub-threshold impedance properties, computational
frameworks have provided direct lines of evidence for degeneracy (Figures 2B,C) in active dendritic spectral tuning (Rathour2012-bu, Rathour2014-pl)." Das2017-nz
***** mainly studied in hippocampal neurons
*** (from intro) role in disease: Ih altered in temporal lobe epilepsy Shin2008-za, Marcelin2009-vy
*** role in oscillations and cross-frequency coupling 
We found that tuning Ih in different cell classes altered network rhythms, providing independent control for
gamma and theta oscillations. Ih modulation also set the level of cross-frequency coupling and timing of gamma
generation relative to the theta cycle. Ih modulation may therefore be an important control point with functional
consequences, since these dynamics are hypothesized to contribute to learning and cognitive function [19–21]. - Neymotin2013-cm
*** we looked at two paradigms for dynamically tuning the impedance response by changing the conductances of HCN and M-type K+ channels at the branch level and
across the whole dendritic arbor in one PC model
**** Changing either HCN or M-type K+ conductance across the whole arbor changed the location-dependent relationships of the impedance profile 
**** We also found that both local and global changes to both HCN and M-type K+ conductance can have produce a wide array of impedance profiles
while also allowing for degeneracy.
***** For instance, changing HCN and M-type K+ conductance by $\pm20\%$ produces a range of impedance profiles, with resonance amplitude varying by over
45M%$\Omega$, resonance frequency over 10 Hz, transfer frequency by 5 Hz, and synchronous frequency by over 6 Hz (\emph{Fig. 9S, T, V, W}). Many of the
possible impedance responses in these ranges can, however, be achieved by multiple combinations of changes to HCN and M-type K+ conductance.
*** While HCN channels are necessary for subthreshold resonance in PCs, M-type K+ channels are just one of the voltage-gated ion channels with
inductive reactance capable of modulating the impedance response; therefore, we have only scratched the surface of possible mechanisms by which 
neurons may dynamically tune their impedance response.  The degeneracy of the impedance response, however, implies that neurons may have multiple 
ways to maintain their impedance profiles in response to Ih modulation, brought about through participation in network oscillations or through pathophysiology.

* [2020-4-13 Mon] - srdjan comments 
** This looks like an attack on strawman. In order to make this statement scientific, the abstract should:
[1] Summarize/state very briefly the published impedance profiles that can be found in dendrites of neocortical L5 pyramidal neurons?;
and [2] Specify in which aspect is your set of impedance profiles different from the “previously established set”.

** Who published the map of impedance profiles in dendrites of pyramidal neurons? Which map is different from the map you hypothesize. 
In which aspect is your hypothesis different from the “previously established impedance profile”?
*** all fair questions, but does the "who" really belong in the abstract?

** The balance of excitatory and inhibitory inputs . . . 
Not true. Active dendritic conductances also play important role.
*** will definitely add that

** Distinguish PCs from IT cells? - I thought that IT cells are PC cells!
Did you meant to say PT instead of PC?
*** Does PT really make sense outside of motor cortex?  PC is pyramidal cell, need some way to distinguish from commissural/IT 

** Ruth Empson does not recognize PT and IT cells. 
Instead, she divides L5 projection pyramidal neurons of the M1 cortical region into 4 categories: 
    1 corticospinal (CSp) neurons, 
    2 corticothalamic (CTh) neurons, 
    3 commissural projecting corticostriatal (CStr) neurons,
    4 commissural projecting corticocortical (CC) neurons.
*** very helpful, but how best to refer to the non-commissural neurons outside of M1 then?

** In the year 2013, a separation based upon two broad projection neuron types (PT and IT) seems limiting and dated (Ruth Empson)
*** seems commissural nuerons don't have location-dependent impedance profiles, but Csp and CTh are (or however we might choose to distinguish them)

** Srdjan is totally confused. Nikolai Dembrow describes COM and CPn pyramidal neurons [ref 9]. 
Craig Kelley somehow uses PC and IT nomenclature. What is the relation between Dembrow and Kelley nomenclatures?
*** maybe subcortical project neurons . . . 

** Unnecessary and Irritating repetition of the term “complex”. We get it -  it is complex. We just need to hear it once in one of the sentences.
*** OK

** (REF) for impedance equations
*** can try to find references, but seems like citing Ohm or Fourier

** It sounds very intellectual, but has no meaning to me. Could you please define “inductive reactances”, before you use it in explaining your point?
*** fair, will add an explanation

** In the context of dendritic integration or synaptic integration, the transfer frequency (what is symbol of Transfer Frequency – Zt#^&?) specifies the
frequency of EPSP leading phase and/or dendritic spike leading phase, at which the efficacy of transfer between the initiation site and the soma is the 
most optimal. For example, two EPSPs of identical amplitude, which propagate from dendrite to soma, will have different somatic amplitude depending on 
the frequency of heir leading phases. 
*** no symbol for transfer frequency, iTo join the video meeting, click this link: https://meet.google.com/xuw-bsyp-pgp
Otherwise, to join by phone, dial +1 320-412-3603 and enter this PIN: 810 319 845#t's the peak frequency of the transfer impedance amplitude
*** not entirely sure if we're talking about the same transfer frequency or using phase in the same manner here?

** If my text above is correct, then we should include this explanation at this point of manuscript, 
because there are readers who are interested in biology primarily, and not physics savvy.

** This Introduction has left us hanging. What is this paper about? I believe, here it is necessary to state two things: 
[1] What is the GAP in knowledge or interesting questions, which remains to be investigated? 
and 
[2] What have we done to address this interesting question - briefly in broad strokes?
*** totally fair 

** The FIRST model [ref 17] does not appear in Fig. 1.
What is the point of calling it The FIRST?
This mismatch between Methods and Figures is a mistake. Readers do not have time to play detective games.
If you call something FIRST, it must be addressed first in the Results section, in Figure 1. I understand that you consider Fig 1 as a Methods figure, 
and Fig. 2 as a Result figure, however I strongly advise that you address FIRST MODEL in the FIRST FIGURE. 
Or change the ordering of models in your narrative, make Acker2008 the “first model”. Also, start the Results section with the Acker figure – Fig. 3.
*** so you touched on why I have it ordered that way, but if confusing will reword/structure things 

** What constitutes a "dendritic segment". Is this based on the, for example n=9 segment feature of NEURON?
*** should change segment -> compartment (more universal term)

** In Figure 1, the amplitude of the injected Chirp current was equal or less than 2 pA. Two picoAmps of current has little or no physiological meaning. 
How can anyone believe that voltage-gated channels are activated with voltage swings of only 0.1 mV (one tenth of one millivolt)?
*** I understand the skepticism, but impedance should be fairly independent of current amplitude as long as we're below spiking threshold, since it's a ratio 
*** NEURON's built in impedance tool looks at much smaller excursions in membrane potential (I believe uV)
*** if voltage-gated ion channels like HCN weren't activated, there wouldn't be any resonance 

** The Figure1 Modeling data has no implications on neuronal physiology, unless the RANGE of current amplitudes were carefully investigated. 
To account for this criticism, I would plot 3 complete Impedance Profiles for the same cell, where the Chirp current amplitude was set at 2 pA, 20 pA and 50 pA.
Then I would publish a conclusion on whether the conclusions of this paper depend, or do not depend, on the Chirp current amplitude. 
Alternatively, how exactly the conclusions of the current paper depend on the Chirp current amplitude, displayed right there in Figure-1. 
*** can include if above argument is not convincing.  

** Fig. 1. The color of the “basilar dendrite” line in the graphs I-L is plum-purple and the color of the dot on cell morphology is sky blue.
 Could you please fix this? Fig. 1. The measurements that should describe OBLIQUE branch  have been made at the branch point between apical trunk 
 and oblique branch.  Could you please move the stimulation and recording site to the middle of the oblique branch, and plot the middle-branch data? Thanks, Srdjan.
*** for sure can move oblique example away from branch point 
*** surprised at the color difference, can't see it on my machine.  I-L look different to C?

morphology - systematic changes - length and radius
voltage clamp 1 compartment each conductance
EPSP frequency vs soma V 
different current injections
kruschavatz
antic@uchc.edu 