#!/bin/bash
rm KoleCell\[0].apic\[80]-batch.sbatch
rm KoleCell\[0].apic\[81]-batch.sbatch
rm KoleCell\[0].apic\[82]-batch.sbatch
rm KoleCell\[0].apic\[83]-batch.sbatch
rm KoleCell\[0].apic\[84]-batch.sbatch
rm KoleCell\[0].apic\[85]-batch.sbatch
rm KoleCell\[0].apic\[86]-batch.sbatch
rm KoleCell\[0].apic\[8]-batch.sbatch
rm KoleCell\[0].apic\[9]-batch.sbatch
rm KoleCell\[0].dend\[0]-batch.sbatch
rm KoleCell\[0].dend\[10]-batch.sbatch
rm KoleCell\[0].dend\[11]-batch.sbatch
rm KoleCell\[0].dend\[12]-batch.sbatch
rm KoleCell\[0].dend\[13]-batch.sbatch
rm KoleCell\[0].dend\[14]-batch.sbatch
rm KoleCell\[0].dend\[15]-batch.sbatch
rm KoleCell\[0].dend\[16]-batch.sbatch
rm KoleCell\[0].dend\[17]-batch.sbatch
rm KoleCell\[0].dend\[18]-batch.sbatch
rm KoleCell\[0].dend\[19]-batch.sbatch
rm KoleCell\[0].dend\[1]-batch.sbatch
rm KoleCell\[0].dend\[20]-batch.sbatch
rm KoleCell\[0].dend\[21]-batch.sbatch
rm KoleCell\[0].dend\[22]-batch.sbatch
rm KoleCell\[0].dend\[23]-batch.sbatch
rm KoleCell\[0].dend\[24]-batch.sbatch
rm KoleCell\[0].dend\[25]-batch.sbatch
rm KoleCell\[0].dend\[26]-batch.sbatch
rm KoleCell\[0].dend\[27]-batch.sbatch
rm KoleCell\[0].dend\[28]-batch.sbatch
rm KoleCell\[0].dend\[29]-batch.sbatch
rm KoleCell\[0].dend\[2]-batch.sbatch
rm KoleCell\[0].dend\[30]-batch.sbatch
rm KoleCell\[0].dend\[31]-batch.sbatch
rm KoleCell\[0].dend\[32]-batch.sbatch
rm KoleCell\[0].dend\[33]-batch.sbatch
rm KoleCell\[0].dend\[34]-batch.sbatch
rm KoleCell\[0].dend\[35]-batch.sbatch
rm KoleCell\[0].dend\[36]-batch.sbatch
rm KoleCell\[0].dend\[37]-batch.sbatch
rm KoleCell\[0].dend\[38]-batch.sbatch
rm KoleCell\[0].dend\[39]-batch.sbatch
rm KoleCell\[0].dend\[3]-batch.sbatch
rm KoleCell\[0].dend\[40]-batch.sbatch
rm KoleCell\[0].dend\[41]-batch.sbatch
rm KoleCell\[0].dend\[42]-batch.sbatch
rm KoleCell\[0].dend\[4]-batch.sbatch
rm KoleCell\[0].dend\[5]-batch.sbatch
rm KoleCell\[0].dend\[6]-batch.sbatch
rm KoleCell\[0].dend\[7]-batch.sbatch
rm KoleCell\[0].dend\[8]-batch.sbatch
rm KoleCell\[0].dend\[9]-batch.sbatch