#!/bin/bash
rm KoleCell\[0\].apic\[0]\-batch.sbatch
rm KoleCell\[0\].apic\[10\]-batch.sbatch
rm KoleCell\[0\].apic\[11\]-batch.sbatch
rm KoleCell\[0\].apic\[12\]-batch.sbatch
rm KoleCell\[0\].apic\[13\]-batch.sbatch
rm KoleCell\[0\].apic\[14\]-batch.sbatch
rm KoleCell\[0\].apic\[15\]-batch.sbatch
rm KoleCell\[0\].apic\[16\]-batch.sbatch
rm KoleCell\[0\].apic\[17\]-batch.sbatch
rm KoleCell\[0\].apic\[18\]-batch.sbatch
rm KoleCell\[0\].apic\[19\]-batch.sbatch
rm KoleCell\[0\].apic\[1]\-batch.sbatch
rm KoleCell\[0\].apic\[20\]-batch.sbatch
rm KoleCell\[0\].apic\[21\]-batch.sbatch
rm KoleCell\[0\].apic\[22\]-batch.sbatch
rm KoleCell\[0\].apic\[23\]-batch.sbatch
rm KoleCell\[0\].apic\[24\]-batch.sbatch
rm KoleCell\[0\].apic\[25\]-batch.sbatch
rm KoleCell\[0\].apic\[26\]-batch.sbatch
rm KoleCell\[0\].apic\[27\]-batch.sbatch
rm KoleCell\[0\].apic\[28\]-batch.sbatch
rm KoleCell\[0\].apic\[29\]-batch.sbatch
rm KoleCell\[0\].apic\[2]\-batch.sbatch
rm KoleCell\[0\].apic\[30\]-batch.sbatch
rm KoleCell\[0\].apic\[31\]-batch.sbatch
rm KoleCell\[0\].apic\[32\]-batch.sbatch
rm KoleCell\[0\].apic\[33\]-batch.sbatch
rm KoleCell\[0\].apic\[34\]-batch.sbatch
rm KoleCell\[0\].apic\[35\]-batch.sbatch
rm KoleCell\[0\].apic\[36\]-batch.sbatch
rm KoleCell\[0\].apic\[37\]-batch.sbatch
rm KoleCell\[0\].apic\[38\]-batch.sbatch
rm KoleCell\[0\].apic\[39\]-batch.sbatch
rm KoleCell\[0\].apic\[3]\-batch.sbatch
rm KoleCell\[0\].apic\[40\]-batch.sbatch
rm KoleCell\[0\].apic\[41\]-batch.sbatch
rm KoleCell\[0\].apic\[42\]-batch.sbatch
rm KoleCell\[0\].apic\[43\]-batch.sbatch
rm KoleCell\[0\].apic\[44\]-batch.sbatch
rm KoleCell\[0\].apic\[45\]-batch.sbatch
rm KoleCell\[0\].apic\[46\]-batch.sbatch
rm KoleCell\[0\].apic\[47\]-batch.sbatch
rm KoleCell\[0\].apic\[48\]-batch.sbatch
rm KoleCell\[0\].apic\[49\]-batch.sbatch
rm KoleCell\[0\].apic\[4]\-batch.sbatch
rm KoleCell\[0\].apic\[50\]-batch.sbatch