* [2020-3-7 Sat] - abstract draft
**
Pyramidal neurons in neocortex have complex input-output relationships that depend on their morhpologies, active and
passive channel distributions, and the nature of their inputs, and which cannot be replicated by their simple 
integrate-and-fire analogs. Measures of the complex impedance response across neurons' dendritic arbors, such as 
resonance and the phase response, can provide intraneuronal functional maps reflecting their intrinsic dynamics and excitability. 
Experimental studies of dendritic impedance show that pyramidal neurons in hippocampal CA1 and neocrotex exhibit distance-dependent
relationships for the resonance and the phase responses with respect to the soma. We present a detailed study of
the complex impedance profiles of biophysically detailed models of neocortical layer 5 pyramidal neurons from 
across neocortex.  While none of these models were designed to fit the impedance response directly, two closely 
recapitulate the distance-dependent relationships of the complex impedance response. The  impedance response is also
dynamically tunable via the activity-dependent expression of voltage-gated ion channels in the dendrites, like HCN channels
and M- and A-type K+ channels. We investigated the roles of different voltage-gated ion channels in tuning the impedance response,
showing that changes in HCN and M-type K+ channel conductances, both locally and across the dendritic arbor, can modulate the
impedance response, producing a wide range of profiles.  We also clearly demonstrate the impedance profile's dependence on cell
morphology.  Although a number of cell models exhibit impedance profiles that diverge from the experimental data, some have 
biologically plausible impedance profiles which may reflect regional variation or cells with different histories and therefore
differently tuned impedance responses. Given the dearth of experimental data on resonance in neocortical pyrmaidal neurons 
from different cortical regions, we hypothesize that neocortical pyramidal neurons have more diverse impedance profiles 
than previously assumed.

* [2020-3-10 Tue] - Introduction outline (cont to [2020-3-13 Fri])
** Neocortical pyramidal neurons
*** Main oupuuts of neocortex 
**** something about I/O relationship
*** Diversity:  
**** Naka2016-rn
"Before surveying the existent literature on layer 5 (L5) inhibitory neurons, we briefly review current
knowledge on the connectivity and physiological properties of L5 pyramidal cells (PCs), as it
provides important context for understanding L5 inhibitory circuits. One feature that distinguishes
L5 from other cortical layers is the diversity of its PCs, which send a myriad of long-range
projections to other cortical and sub-cortical structures (Levesque1996-hf, Veinante2000-gg,
Hattox2007-km, Aronoff2010-do, Harris2015-te). This simple anatomical fact establishes L5 as a primary 
cortical layer involved in the top-down control of other brain areas. Exactly how L5 circuits parse information to 
influence downstream circuits and control behavior is one of the central questions in neuroscience. Even though L5 is
conventionally thought of as primarily an output layer, L5 PCs also receive direct thalamocortical input (Agmon1992-mi,
Meyer2010-pe, Wimmer2010-lq, Oberlaender2012-fh, Rah2013-kr) and can be driven by thalamic activity alone (Constantinople2013-bq), 
suggesting that L5 is an important input layer as well. L5 PCs also receive input from all cortical layers and
are thus uniquely positioned to integrate nearly every local and afferent pathway in the cortex
(Markram2015-zg). Without exception, signals transmitted via these pathways invoke a mixture
of synaptic excitation and inhibition (reviewed in Isaacson2011-qs). Thus inhibition
onto L5 PCs, the focus of this review, is crucial for nearly every aspect of L5 function."
*** Active conductances
**** One of the main distinguishing factors between PT and IT neurons is the greater expression of 
voltage-gated ion channels, like HCN. Oswald2013-lh
**** "In responseto dynamic stimuli,  COM neurons act as low-pass filters, whereas CPn neurons act 
as bandpass filters, resonating in the theta frequency range (3– 6Hz)." Dembrow2010-lb
**** mediate coincidence detection Das2015-mh, Dewell2019-ra
**** Ih has also been shown to "interact with somato-dendritic structure to determine frequency response to
weak alternating electric field stimulation" Toloza2018-vh
****  "the inhibitory action of Ih was caused by its interaction with the delayed-rectifier M-type K1 current. In this manner, Ih can
enhance spike firing in response to an EPSP when spike threshold is low and can inhibit firing when spike threshold is high." George2009-ad
***** check w/ salva/joao - pretty sure this is the paper proposing that Ih modulation determines planning versus action 

** Impedance as comprehensive tool for studying subthreshold dynamics
*** As mentioned above, PT cells act as bandpass filters as characterized by their impedance profiles.
*** some  background on impedance Puil1986-uv, Jaffe1999-pb: 
**** complex function (resistance and reactance) from which can calculate the amplitude and phase 
**** input vs transfer
**** resonance - peak |Z| at some frequency - driven by inductive reactance imparted by voltage-gated ion channels like HCN, M-type K+, and K-type K+ channels
**** resonance strength (Q-factor as in Dewell2019-ra)
**** transfer frequency - resonance frequency of the transfer impedance amplitude 
**** leading phase response - changes in V preceed changes in I, driven by the balance of capacitive and inductive reactances
**** synchronous frequency - frequency at which V and I are synchronous

*** importance of impedance
**** resonance:  "Apart from invertebrate giant axons from where initial evidence came, direct evidence for the presence of electrical resonance
also came from experiments on numerous neuronal subtypes of the central and peripheral nervous system (Crawford1981-av, Puil1988-ca,
Hutcheon2000-gs, Pike et al., 2000). Subthreshold resonance in local responses and in dendrite-to-soma transfer endows neurons with the ability to
discriminate inputs based upon their frequency content."
**** phase response: "the impedance phase profile quantifies the temporal dynamics between voltage and current. It has been shown that presence
of inductive reactance in neuronal membrane causes the voltage response to lead the injected oscillatory current. The balance between capacitive and
inductive reactances determines both the optimal lead frequency and the frequency bandwidth over which the voltage leads the current, providing a
potential mechanism by which the subthreshold membrane dynamics of the neuron may maintain a phase relationship with an ongoing oscillation
(Mauro1961-ys, Cole, 1968, Sabah1969-at, Mauro1970-km, Hu2002-ga, Hu2009-qb, Ulrich2002-dd, Cook2007-cz, Narayanan2008-zw,
Vaidya2013-sx)." Das2017-nz
**** relation between subthreshold resonance and suprathreshold resonance via STA Das2015-mh
*** By determining these factors across the dendritic arbor, we can produce intraneuronal functional maps characterizing
the neuron's intrinsic dynamics and excitability Narayanan2012-hn 

** Experimental evidence of location dependence 
*** relationships between aspects of the complex impedance and distance from the soma have been described in pyramidal neurons from CA1 and neocortex
Das2017-nz, Narayanan2007-gw, Ulrich2002-dd, Dembrow2015-zb
**** first observed in PT neurons from somatosensory cortex.  Saw roughly linear relationships between distance and transfer impedance amplitude with
strength increasing with distance from the soma. Ulrich2002-dd
**** Dembrow et al additionally saw distance-dependence in the resoance frequency and phase response Dembrow2015-zb
**** in both above studies resonance and synchronous frequencies were found in the theta range (3-10 Hz), but also sampled a fairly small fraction of the 
dendritic arbor (120-280 um and 200-600 um respectively)

** dynamic tunability and degeneracy impedance profile
*** Tunability
**** dynamically tunable subthreshold resonance along the neuronal topograph (Magee2005-oq, Narayanan2007-gw, Narayanan2008-zw, Sjostrom2008-sz, 
Hu2009-qb, Rathour2012-am, Rathour2012-bu) Das2017-nz
**** LTP induces changes in impedance profile Narayanan2007-gw
*** Degeneracy:
**** "With reference to sub- and supra-threshold frequency selectivity in neurons, several studies have demonstrated multi-channel regulation
of somatodendritic spectral selectivity. Specifically, studies pertaining to sub-threshold resonance and phase dynamics have shown that impedance properties 
mediated by HCN channel could be significantly modulated by the presenc eof other sub-threshold conductances and by morphological characteristics 
(Hutcheon2000-gs, Hu2002-ga, 2009, Narayanan2008-zw, Zemankovics2010-zt, Rathour2012-bu, Dhupia2014-ad, Rathour2016-vv). While these studies
elucidated the role of individual conductances in modulating sub-threshold impedance properties, computational
frameworks have provided direct lines of evidence for degeneracy (Figures 2B,C) in active dendritic spectral tuning (Rathour2012-bu, Rathour2014-pl)." Das2017-nz
***** mainly studied in hippocampal neurons
*** role in disease: Ih altered in temporal lobe epilepsy Shin2008-za, Marcelin2009-vy

* [2020-3-12 Thu] 
** fairly satisfied w/ intro outline
** going with frontiers in neuroscience as target journal (in part becasue formatting is easy)

* [2020-3-13 Fri] - further along with intro
** may want to consolidate explanation and importance of impedance while separating amplitude/resonance and phase

* [2020-3-14 Sat] - finished with draft of intro, methods outline  (con't to [2020-3-16 Mon])
** General stuff:
*** All models have perviously been published and are freely available on modelDB
*** Simulations were performed using NEURON in Python Hines2009-qx
*** Code for simulation, analysis, and visualization was written in Python and MATLAB (Natick, Ma) and is available on GitHub (https://github.com/suny-downstate-medical-center/L5PYR_Resonance)

** Focus on 5  models
*** Kole2008-aj
**** Wistar rats, 2-4 weeks old, somatosensory cortex
**** channels densities were adjusted primarily to account for perisomatic spiking actiivity:
"The model included a high-voltage-activated K+ channel (Kv)16, a faster
low-voltage activated Kv1-like K+ channel (‘Kv1’), as described49, and a slowly-activating and non-inactivating M-type K+ channel (‘Km’)16. Potassium
channel densities were adjusted to obtain fast action potential repolarization
and large amplitude afterhyperpolarizations in the distal AIS13. The density of
Kv, Kv1 and Km were set to 20, 100 and 5 pS mm–2, respectively, in the soma,
dendrites and inter-nodal sections, and increased linearly with distance from
the axon hillock in the AIS to 2,000 pS mm–2 in the distal AIS and nodes for
Kv and Kv1, and to 50 pS mm–2 for Km. The K+ reversal potential was set
to –85 mV. Ih channels were included in the soma and dendrites with an
exponential increase in density with distance from the soma, and kinetics and
voltage dependence as described previously50." 50: Kole2006-bm
*** Acker2009-yj
**** Sprague–Dawley rats (postnatal day 21 [P21] to P33), frontal cortex
**** fit using voltage-sensitive dye imaging focusing on back-propagating APs in basal dendrites 
"The model was fit to experimental data using the
following approach: AP waveforms from simulations were analyzed
and amplitude data were averaged over the basal dendrites (Fig. 6B).
Half-widths and latencies were calculated in exactly the same way as
with the optical AP waveforms (Supplemental Fig. S5) and were
averaged over the model basal dendrites. The model data averaged
over the basal dendrites were taken as the fit data. AP amplitude ratios
TTX/Control and AP amplitude ratios 4-AP/Control were used to fit
the model.
**** channel distributions
. . . Basal dendritic sodium and A-type potassium conductance
distributions were assumed linear and were systematically varied over
a wide range over a four-dimensional parameter space to determine
the best-fit values of these model parameters (Supplemental Fig. S7).
Other parameters, such as delayed rectifier potassium conductance,
leak conductance, and somatic conductances, were manually varied to
find the lowest possible overall model fit. This was done by first
determining the sensitivities of AP amplitudes, half-widths, and latencies
 to each model parameter and using this information to modify
parameters and improve fits before finally fitting the basal sodium and
A-type potassium distributions. An automated optimization approach
based on a genetic algorithm (Keren et al. 2005), if feasible, would
allow a larger parameter space to be searched exhaustively and could
potentially lead to improved overall fits, something that could be
pursued in future studies."
*** Hay2011-if
**** P36 Wistar rat 
**** model fit to perisomatic and backpropagating spiking
**** channel distributions:
"Dendritic channel distribution. All dendritic channels
except for Ih, CaLVA and CaHVA were uniformly distributed. Ihchannels were distributed on the apical dendrites using an
exponential density function suggested in [13]: gsoma: ð{0:8696z 2:087: e x
323Þ, where x is the distance from the soma in mm, with gsoma = 1 pS/mm2 .
The density of Ih on the basal dendrites was set to be uniform as suggested in [10]."
10: Nevian2007-gw  13: Kole2006-bm
*** Neymotin2017-dr
**** might leave out or stick in supplements, both because mice and wonky
**** Mice (strain: C57Bl/6J; Jackson Laboratories) postnatal day (P) 21,
**** channel distributions:
Somatic and dendritic compartments
additionally contained CaL, CaN, BK, and HCN channels. KD was
present in the soma and at 20 times somatic density in the axon. The
axon contained only leak, Na, KA, Kdr, and KD ion channels. Basal
dendrites contained uniform density of all their channels. Apical
dendrite HCN channel density increased exponentially with distance
from soma until reaching the nexus with apical dendrite tufts, where
the HCN channel density plateaus at 0.00565 S/cm2 (Harnett et al.
2015). This exponential increase of HCN channel density within the
main apical trunk was set to gh·exp(d/h), where d is distance of the
apical dendrite compartment from soma and h is the length constant,
defined as dnexus/log(0.00565/gh), dnexus is distance from soma to
nexus (300 m), and gh is somatic HCN channel density. Harnett2015-sj
**** fitting was mostly focused on preisomatic spiking activity:
. Focusing on spike times, we also
provided some fitness function redundancy by using both
overall spiking rate (F–I), along with spike timing [instantaneous firing rate (IFR)]. The degree of redundancy of these two
measures was demonstrated in the final archive (Fig. 2, A and
C). We included subthreshold fit, determined initially by
PRAXIS, as an EMO fitness function as well so as not to lose
fitness for this criterion while optimizing for the others.
*** allen institute cell(s) Reimann2013-mg, Shai2015-ff, Markram2015-zg
**** based on data from primary visual cortex (V1) of C57BL/6 mice, P35-62
**** Modified version of an earlier model \citep{Hay2011-if}
**** major change to the original:"We change the Ih conductance to be constant in the dendritic tree, instead of exponentially increasing as a function of distance from
the soma, to fit the subthreshold data. The change to Ih conductance accounted for the differences between dendritic sag, dendritic resting membrane potential relative 
to the soma, and dendritic input resistance in our experiments compared to those in rat L5 somatosensory cortex."


** simulations 
*** Impedance Profiles:
****Each dendritic segment was stimulated with a subthreshold chirp-waveform current injection, and membrane potential was recorded
from the site of stimulation and at the soma.
***** For generating impednace profiles, the chirp-waveform instantaneous frequency changed linearly spanned 0.5-50 Hz over 50s.
***** For investigating bimodal phase response, the chirp-waveform spanned 0.5-100 Hz over 100s.
***** in experiments, typically 0.5-20 Hz (citations)
**** We computed Z$_{in}$ and Z$_c$ and associated measures from each of the recorded waveforms via \emph{Eq. 1-3}.
***** focused on six measures of the impedance response: 1) $|$Z$_{in}|$ resonance amplitude, 2) $|$Z$_{in}|$ resonance frequency,
3) $|$Z$_{in}|$ Q-factor, 4) $|$Z$_{c}|$ transfer frequency, 5) $\Phi_{in}$ leading phase bandwidth, and 6) $\Phi_{in}$ synchronous frequency. 
*** Influence of morphology
**** same parameters as above, used biophysics template and three morphologies from Hay2011-if
*** Ih and Im 
**** used cell model from Kole2008-aj, only one that had Ih and Im distributed throughout the dendritic arbor.
**** varied Ih and Im conductance in 5% increments up to +/- 20% either at the branch level or across the whole dendritic arbor 


* [2020-3-15 Sun] - bimodal phase response
** L5PCtemplate[0].apic[91].mat 
* [2020-3-16 Mon] - methods con't, added in sam's cell, going to add in allen institute
* [2020-3-17 Tue]
** bimodal phase response, a couple OK examples, not sure if it warrants figure / mentioning
* [2020-3-19 Thu] - working on putting figures together properly
* [2020-3-20 Fri] - finished up figures
** allen exmaple 1: 497233139, 2: 497232419
* [2020-3-21 Sat] 
** table of basic model info