* [2020-3-7 Sat] - abstract draft
**
Pyramidal neurons in neocortex have complex input-output relationships that depend on their morhpologies, active and
passive channel distributions, and the nature of their inputs, and which cannot be replicated by their simple 
integrate-and-fire analogs. Measures of the complex impedance response across neurons' dendritic arbors, such as 
resonance and the phase response, can provide intraneuronal functional maps reflecting their intrinsic dynamics and excitability. 
Experimental studies of dendritic impedance show that pyramidal neurons in hippocampal CA1 and neocrotex exhibit distance-dependent
relationships for the resonance and the phase responses with respect to the soma. We present a detailed study of
the complex impedance profiles of biophysically detailed models of neocortical layer 5 pyramidal neurons from 
across neocortex.  While none of these models were designed to fit the impedance response directly, two closely 
recapitulate the distance-dependent relationships of the complex impedance response. The  impedance response is also
dynamically tunable via the activity-dependent expression of voltage-gated ion channels in the dendrites, like HCN channels
and M- and A-type K+ channels. We investigated the roles of different voltage-gated ion channels in tuning the impedance response,
showing that changes in HCN and M-type K+ channel conductances, both locally and across the dendritic arbor, can modulate the
impedance response, producing a wide range of profiles.  We also clearly demonstrate the impedance profile's dependence on cell
morphology.  Although a number of cell models exhibit impedance profiles that diverge from the experimental data, some have 
biologically plausible impedance profile    s which may reflect regional variation or cells with different histories and therefore
differently tuned impedance responses. In light of the dirth of experimental data on resonance in neocortical pyrmaidal neurons 
from different cortical regions, we hypothesize that neocortical pyramidal neurons have more diverse impedance profiles 
than previously assumed.
* [2020-3-10 Tue] - Introduction outline (cont to [2020-3-12 Thu])
** Neocortical pyramidal neurons
*** Main oupuuts of neocortex 
**** something about I/O relationship
*** Diversity:  
**** Naka2016-rn
"Before surveying the existent literature on layer 5 (L5) inhibitory neurons, we briefly review current
knowledge on the connectivity and physiological properties of L5 pyramidal cells (PCs), as it
provides important context for understanding L5 inhibitory circuits. One feature that distinguishes
L5 from other cortical layers is the diversity of its PCs, which send a myriad of long-range
projections to other cortical and sub-cortical structures (Levesque1996-hf; Veinante2000-gg;
Hattox2007-km; Aronoff2010-do; Harris2015-te). This simple anatomical fact establishes L5 as a primary 
cortical layer involved in the top-down control of other brain areas. Exactly how L5 circuits parse information to 
influence downstream circuits and control behavior is one of the central questions in neuroscience. Even though L5 is
conventionally thought of as primarily an output layer, L5 PCs also receive direct thalamocortical input (Agmon1992-mi;
Meyer2010-pe; Wimmer2010-lq; Oberlaender2012-fh; Rah2013-kr) and can be driven by thalamic activity alone (Constantinople2013-bq), 
suggesting that L5 is an important input layer as well. L5 PCs also receive input from all cortical layers and
are thus uniquely positioned to integrate nearly every local and afferent pathway in the cortex
(Markram2015-zg). Without exception, signals transmitted via these pathways invoke a mixture
of synaptic excitation and inhibition (reviewed in Isaacson2011-qs). Thus inhibition
onto L5 PCs, the focus of this review, is crucial for nearly every aspect of L5 function."
*** Active conductances
**** One of the main distinguishing factors between PT and IT neurons is the greater expression of 
voltage-gated ion channels, like HCN. Oswald2013-lh
**** "In responseto dynamic stimuli,  COM neurons act as low-pass filters, whereas CPn neurons act 
as bandpass filters, resonating in the theta frequency range (3– 6Hz)." Dembrow2010-lb
**** mediate coincidence detection Das2015-mh, Dewell2019-ra
**** Ih has also been shown to "interact with somato-dendritic structure to determine frequency response to
weak alternating electric field stimulation" Toloza2018-vh
****  "the inhibitory action of Ih was caused by its interaction with the delayed-rectifier M-type K1 current. In this manner, Ih can
enhance spike firing in response to an EPSP when spike threshold is low and can inhibit firing when spike threshold is high." George2009-ad
***** check w/ salva/joao - pretty sure this is the paper proposing that Ih modulation determines planning versus action 

** Impedance as comprehensive tool for studying subthreshold dynamics
*** As mentioned above, PT cells act as bandpass filters as characterized by their impedance profiles.
*** some  background on impedance Puil1986-uv, Jaffe1999-pb: 
**** complex function (resistance and reactance) from which can calculate the amplitude and phase 
**** input vs transfer
**** resonance - peak |Z| at some frequency - driven by inductive reactance imparted by voltage-gated ion channels like HCN, M-type K+, and K-type K+ channels
**** resonance strength (Q-factor as in Dewell2019-ra)
**** transfer frequency - resonance frequency of the transfer impedance amplitude 
**** leading phase response - changes in V preceed changes in I, driven by the balance of capacitive and inductive reactances
**** synchronous frequency - frequency at which V and I are synchronous

*** importance of impedance
**** resonance:  "Apart from invertebrate giant axons from where initial evidence came, direct evidence for the presence of electrical resonance
also came from experiments on numerous neuronal subtypes of the central and peripheral nervous system (Crawford and Fettiplace, 1981; Puil et al.,1986;
Hutcheon2000-gs; Pike et al., 2000). Subthreshold resonance in local responses and in dendrite-to-soma transfer endows neurons with the ability to
discriminate inputs based upon their frequency content."
**** phase response: "the impedance phase profile quantifies the temporal dynamics between voltage and current. It has been shown that presence
of inductive reactance in neuronal membrane causes the voltage response to lead the injected oscillatory current. The balance between capacitive and
inductive reactances determines both the optimal lead frequency and the frequency bandwidth over which the voltage leads the current, providing a
potential mechanism by which the subthreshold membrane dynamics of the neuron may maintain a phase relationship with an ongoing oscillation
(Mauro1961-ys; Cole, 1968; Sabah1969-at; Mauro1970-km; Hu2002-ga, Hu2009-qb; Ulrich2002-dd; Cook2007-cz; Narayanan2008-zw;
Vaidya2013-sx)." Das2017-nz
**** relation between subthreshold resonance and suprathreshold resonance via STA Das2015-mh
*** By determining these factors across the dendritic arbor, we can produce intraneuronal functional maps characterizing
the neuron's intrinsic dynamics and excitability Narayanan2012-hn 

** Experimental evidence of location dependence 
*** relationships between aspects of the complex impedance and distance from the soma have been described in pyramidal neurons from CA1 and neocortex
Das2017-nz, Narayanan2007-gw, Ulrich2002-dd, Dembrow2015-zb
**** first observed in PT neurons from somatosensory cortex.  Saw roughly linear relationships between distance and transfer impedance amplitude with
strength increasing with distance from the soma. Ulrich2002-dd
**** Dembrow et al additionally saw distance-dependence in the resoance frequency and phase response Dembrow2015-zb
**** in both above studies resonance and synchronous frequencies were found in the theta range (3-10 Hz), but also sampled a fairly small fraction of the 
dendritic arbor (120-280 um and 200-600 um respectively)

** dynamic tunability and degeneracy impedance profile
*** Tunability
**** dynamically tunable subthreshold resonance along the neuronal topograph (Magee2005-oq; Narayanan2007-gw; Narayanan2008-zw; Sjostrom2008-sz; 
Hu2009-qb; Rathour2012-am; Rathour2012-bu) Das2017-nz
**** LTP induces changes in impedance profile Narayanan2007-gw
*** Degeneracy:
**** "With reference to sub- and supra-threshold frequency selectivity in neurons, several studies have demonstrated multi-channel regulation
of somatodendritic spectral selectivity. Specifically, studies pertaining to sub-threshold resonance and phase dynamics have shown that impedance properties 
mediated by HCN channel could be significantly modulated by the presenc eof other sub-threshold conductances and by morphological characteristics 
(Hutcheon2000-gs; Hu2002-ga, 2009; Narayanan2008-zw; Zemankovics2010-zt; Rathour2012-bu; Dhupia2014-ad; Rathour2016-vv). While these studies
elucidated the role of individual conductances in modulating sub-threshold impedance properties, computational
frameworks have provided direct lines of evidence for degeneracy (Figures 2B,C) in active dendritic spectral tuning (Rathour2012-bu; Rathour2014-pl)." Das2017-nz
***** mainly studied in hippocampal neurons
*** role in disease: Ih altered in temporal lobe epilepsy Shin2008-za, Marcelin2009-vy